# This workflow will build UML Designer with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Test UML Designer

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.11.0
      with:
        java-version: '17'
        java-distribution: 'temurin'
        maven-version: '3.9.5'
    - name: Build uml designer
      run: mvn clean verify --batch-mode --update-snapshots --fail-at-end --file pom.xml
    - name: Build uml designer products
      run: mvn clean verify  --batch-mode --update-snapshots --fail-at-end --file releng/org.obeonetwork.dsl.uml2.product.parent/pom.xml
    - name: Prepare deployment
      run: ./prepare-deploy-local-dir.sh $GITHUB_REF_NAME && tar czvf UMLDesigner-pages.tar.gz $GITHUB_REF_NAME
    - name: Attach Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
    - name: Release uml designer
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          packaging/org.obeonetwork.dsl.uml2.product/target/products/UMLDesigner-*.*
          UMLDesigner-pages.tar.gz